// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * PowerPoint Export Service
 *
 * Generates a single widescreen (16:9) .pptx slide from the current diagram
 * canvas image.  The slide theme (dark / light) matches the app's current
 * colour mode so the exported slide looks exactly like what the user sees.
 *
 * Library: PptxGenJS v4 (client-side, no backend required)
 */

import PptxGenJS from 'pptxgenjs';
import { generateModelFilename } from '../utils/modelNaming';

// ─── Theme palettes ───────────────────────────────────────────────────────────

interface SlideTheme {
  bg: string;
  headerBg: string;
  accent: string;
  titleText: string;
  metaText: string;
  footerText: string;
}

const DARK_THEME: SlideTheme = {
  bg: '1e293b',       // slate-800
  headerBg: '0f172a', // slate-900
  accent: '0078d4',   // Azure blue
  titleText: 'ffffff',
  metaText: '94a3b8', // slate-400
  footerText: '475569', // slate-600
};

const LIGHT_THEME: SlideTheme = {
  bg: 'f8fafc',       // slate-50
  headerBg: 'e2e8f0', // slate-200
  accent: '0078d4',   // Azure blue
  titleText: '0f172a', // slate-900
  metaText: '475569',  // slate-600
  footerText: '94a3b8', // slate-400
};

// ─── Slide layout constants (inches, LAYOUT_WIDE = 13.33" × 7.5") ────────────

const W = 13.33;  // slide width
const ACCENT_H = 0.07;
const HEADER_H = 0.83;
const HEADER_END = ACCENT_H + HEADER_H;   // 0.9"
const SEP_H = 0.04;
const IMAGE_Y = HEADER_END + SEP_H + 0.06; // ~1.0"
const IMAGE_X = 0.2;
const IMAGE_W = W - IMAGE_X * 2;           // 12.93"
const FOOTER_H = 0.28;
const FOOTER_Y = 7.5 - FOOTER_H - 0.08;   // ~7.14"
const IMAGE_H = FOOTER_Y - IMAGE_Y - 0.1; // remaining body height

// ─── Public export function ───────────────────────────────────────────────────

export interface PptxExportOptions {
  diagramName: string;
  author: string;
  date: string;
  isDarkMode: boolean;
}

/**
 * Build and download a single-slide PPTX containing the diagram image.
 * Returns the generated filename.
 */
export async function exportDiagramAsPptx(
  imageDataUrl: string,
  options: PptxExportOptions,
): Promise<string> {
  const { diagramName, author, date, isDarkMode } = options;
  const t = isDarkMode ? DARK_THEME : LIGHT_THEME;

  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = author;
  pptx.title = diagramName;
  pptx.subject = 'Azure Architecture Diagram';
  pptx.company = 'Microsoft Azure';

  const slide = pptx.addSlide();

  // ── Background ──────────────────────────────────────────────────────────────
  slide.background = { color: t.bg };

  // ── Top accent bar (Azure blue) ─────────────────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: W, h: ACCENT_H,
    fill: { color: t.accent },
    line: { color: t.accent, width: 0 },
  });

  // ── Header strip ────────────────────────────────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: ACCENT_H, w: W, h: HEADER_H,
    fill: { color: t.headerBg },
    line: { color: t.headerBg, width: 0 },
  });

  // ── Diagram title ────────────────────────────────────────────────────────────
  slide.addText(diagramName, {
    x: 0.35, y: ACCENT_H + 0.05, w: 9.5, h: HEADER_H - 0.1,
    fontSize: 24,
    bold: true,
    color: t.titleText,
    fontFace: 'Yu Gothic UI',
    valign: 'middle',
    wrap: true,
  });

  // ── Author + date (right side of header) ────────────────────────────────────
  slide.addText(`${author}  ·  ${date}`, {
    x: 9.9, y: ACCENT_H + 0.05, w: 3.08, h: HEADER_H - 0.1,
    fontSize: 10,
    color: t.metaText,
    fontFace: 'Yu Gothic UI',
    align: 'right',
    valign: 'middle',
  });

  // ── Thin separator between header and image ──────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: HEADER_END, w: W, h: SEP_H,
    fill: { color: t.accent },
    line: { color: t.accent, width: 0 },
  });

  // ── Diagram image ────────────────────────────────────────────────────────────
  slide.addImage({
    data: imageDataUrl,
    x: IMAGE_X,
    y: IMAGE_Y,
    w: IMAGE_W,
    h: IMAGE_H,
    sizing: { type: 'contain', w: IMAGE_W, h: IMAGE_H },
  });

  // ── Footer text ──────────────────────────────────────────────────────────────
  slide.addText('Generated by Azure Architecture Diagram Builder  ·  microsoft.com/azure', {
    x: 0.35, y: FOOTER_Y, w: W - 0.7, h: FOOTER_H,
    fontSize: 8,
    color: t.footerText,
    fontFace: 'Yu Gothic UI',
    valign: 'middle',
  });

  const fileName = generateModelFilename('azure-diagram-slide', 'pptx');
  await pptx.writeFile({ fileName });
  return fileName;
}

// ═══════════════════════════════════════════════════════════════════════════
//  Customer-ready deck (multi-slide)
// ═══════════════════════════════════════════════════════════════════════════

// PptxGenJS's runtime shapes are richer than its exported types in a few spots
// (e.g. table cell options); a narrow local alias keeps the call-sites clean.
type Slide = ReturnType<PptxGenJS['addSlide']>;

export interface DeckService {
  name: string;
  category?: string;
  group?: string;
}

export interface DeckPillar {
  pillar: string;
  score: number;
  /** Maturity label, e.g. "Adequate, with gaps" (falls back to a score band). */
  maturity?: string;
}

export interface DeckFinding {
  severity: 'critical' | 'high' | 'medium' | 'low' | string;
  category: string;
  issue: string;
  recommendation?: string;
}

export interface DeckValidation {
  overallScore: number;
  /** Overall maturity label, e.g. "Adequate, with gaps". */
  overallLabel?: string;
  summary?: string;
  pillars: DeckPillar[];
  findings: DeckFinding[];
  modelUsed?: string;
}

export interface DeckRegionCost {
  name: string;
  flag?: string;
  monthly: number;
  annual: number;
  isCurrent?: boolean;
  isCheapest?: boolean;
}

export interface DeckCost {
  totalMonthly: number;
  annual?: number;
  currency: string;
  term?: string;
  region?: string;
  pricesAsOf?: string;
  /** Fixed (predictable) vs usage-based split, when derivable. */
  fixedCost?: number;
  usageCost?: number;
  byCategory: { category: string; cost: number; percentage: number }[];
  topServices: { serviceName: string; cost: number; tier?: string; percentage?: number }[];
  /** Multi-region comparison (sorted cheapest-first), when computed. */
  regions?: DeckRegionCost[];
}

export interface ArchitectureDeckOptions extends PptxExportOptions {
  /** The original natural-language prompt ("the napkin"). */
  prompt?: string;
  /** Model that generated the architecture. */
  model?: string;
  /** Flat service inventory derived from the diagram nodes. */
  services: DeckService[];
  /** Optional WAF validation summary — a slide is added only when present. */
  validation?: DeckValidation | null;
  /** Optional cost estimate — a slide is added only when present. */
  cost?: DeckCost | null;
}

const BODY_TOP = HEADER_END + SEP_H + 0.18; // ~1.12"
const BODY_H = FOOTER_Y - BODY_TOP - 0.1;

function scoreColor(s: number): string {
  return s >= 80 ? '16a34a' : s >= 60 ? 'f59e0b' : 'dc2626';
}
function scoreBand(s: number): string {
  return s >= 80 ? 'Well-Architected' : s >= 60 ? 'Needs attention' : 'At risk';
}
function severityColor(sev: string): string {
  const s = sev.toLowerCase();
  return s === 'critical' || s === 'high' ? 'dc2626' : s === 'medium' ? 'f59e0b' : '0078d4';
}
function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1).trimEnd() + '…' : s;
}
function money(n: number, currency: string): string {
  const sym = currency === 'USD' ? '$' : '';
  return `${sym}${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}

/** Shared header bar + separator + footer chrome for a content slide. */
function addChrome(pptx: PptxGenJS, slide: Slide, t: SlideTheme, title: string, meta?: string): void {
  slide.background = { color: t.bg };
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: W, h: ACCENT_H, fill: { color: t.accent }, line: { color: t.accent, width: 0 } });
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: ACCENT_H, w: W, h: HEADER_H, fill: { color: t.headerBg }, line: { color: t.headerBg, width: 0 } });
  slide.addText(title, { x: 0.35, y: ACCENT_H + 0.05, w: 9.5, h: HEADER_H - 0.1, fontSize: 22, bold: true, color: t.titleText, fontFace: 'Yu Gothic UI', valign: 'middle', wrap: true });
  if (meta) {
    slide.addText(meta, { x: 9.9, y: ACCENT_H + 0.05, w: 3.08, h: HEADER_H - 0.1, fontSize: 10, color: t.metaText, fontFace: 'Yu Gothic UI', align: 'right', valign: 'middle' });
  }
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: HEADER_END, w: W, h: SEP_H, fill: { color: t.accent }, line: { color: t.accent, width: 0 } });
  slide.addText('Generated by Azure Architecture Diagram Builder  ·  microsoft.com/azure', { x: 0.35, y: FOOTER_Y, w: W - 0.7, h: FOOTER_H, fontSize: 8, color: t.footerText, fontFace: 'Yu Gothic UI', valign: 'middle' });
}

/** Slide 1 — title / cover. */
function addTitleSlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  const slide = pptx.addSlide();
  slide.background = { color: t.headerBg };
  // Left accent band
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.28, h: 7.5, fill: { color: t.accent }, line: { color: t.accent, width: 0 } });
  slide.addText('AZURE ARCHITECTURE', { x: 0.9, y: 1.5, w: 11.5, h: 0.4, fontSize: 14, bold: true, color: t.accent, fontFace: 'Yu Gothic UI', charSpacing: 3 });
  slide.addText(o.diagramName, { x: 0.9, y: 2.0, w: 11.5, h: 1.6, fontSize: 40, bold: true, color: t.titleText, fontFace: 'Yu Gothic UI', valign: 'top', wrap: true });
  slide.addText(`${o.author}   ·   ${o.date}`, { x: 0.9, y: 3.7, w: 11.5, h: 0.4, fontSize: 14, color: t.metaText, fontFace: 'Yu Gothic UI' });
  if (o.prompt) {
    slide.addText([
      { text: 'Brief:  ', options: { bold: true, color: t.metaText } },
      { text: truncate(o.prompt, 420), options: { color: t.metaText } },
    ], { x: 0.9, y: 4.35, w: 11.5, h: 1.7, fontSize: 13, fontFace: 'Yu Gothic UI', valign: 'top', italic: true });
  }
  if (o.model) {
    slide.addText(`Generated with ${o.model}`, { x: 0.9, y: 6.6, w: 11.5, h: 0.35, fontSize: 10, color: t.footerText, fontFace: 'Yu Gothic UI' });
  }
}

/** Slide 2 — the diagram image. */
function addDiagramSlide(pptx: PptxGenJS, t: SlideTheme, imageDataUrl: string, o: ArchitectureDeckOptions): void {
  const slide = pptx.addSlide();
  addChrome(pptx, slide, t, o.diagramName, `${o.author}  ·  ${o.date}`);
  slide.addImage({ data: imageDataUrl, x: IMAGE_X, y: IMAGE_Y, w: IMAGE_W, h: IMAGE_H, sizing: { type: 'contain', w: IMAGE_W, h: IMAGE_H } });
}

/** Slide 3 — service inventory. */
function addServicesSlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  if (!o.services.length) return;
  const slide = pptx.addSlide();
  addChrome(pptx, slide, t, `Services  ·  ${o.services.length} components`);

  const MAX_ROWS = 20;
  const shown = o.services.slice(0, MAX_ROWS);
  const header = [
    { text: 'Service', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
    { text: 'Category', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
    { text: 'Zone / Group', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
  ];
  const rows = shown.map((s) => [
    { text: s.name, options: { color: t.titleText } },
    { text: s.category || '—', options: { color: t.metaText } },
    { text: s.group || '—', options: { color: t.metaText } },
  ]);
  slide.addTable([header, ...rows], {
    x: 0.35, y: BODY_TOP, w: W - 0.7, h: BODY_H,
    colW: [5.2, 3.9, 3.53],
    fontSize: 12, fontFace: 'Yu Gothic UI',
    border: { type: 'solid', color: t.headerBg, pt: 1 },
    valign: 'middle', rowH: 0.32,
  });
  if (o.services.length > MAX_ROWS) {
    slide.addText(`+ ${o.services.length - MAX_ROWS} more services`, { x: 0.35, y: FOOTER_Y - 0.32, w: 6, h: 0.3, fontSize: 10, italic: true, color: t.footerText, fontFace: 'Yu Gothic UI' });
  }
}

/** Slide 4a — WAF executive summary (only when validation provided). */
function addValidationSummarySlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  const v = o.validation;
  if (!v) return;
  const slide = pptx.addSlide();
  addChrome(pptx, slide, t, 'Well-Architected review', v.modelUsed ? `Assessed with ${v.modelUsed}` : undefined);

  // Big score block (left)
  slide.addShape(pptx.ShapeType.roundRect, { x: 0.35, y: BODY_TOP, w: 3.0, h: 2.35, fill: { color: t.headerBg }, line: { color: scoreColor(v.overallScore), width: 2 }, rectRadius: 0.08 });
  slide.addText(`${Math.round(v.overallScore)}`, { x: 0.35, y: BODY_TOP + 0.2, w: 3.0, h: 1.25, fontSize: 58, bold: true, color: scoreColor(v.overallScore), align: 'center', fontFace: 'Yu Gothic UI' });
  slide.addText('/ 100', { x: 0.35, y: BODY_TOP + 1.42, w: 3.0, h: 0.32, fontSize: 13, color: t.metaText, align: 'center', fontFace: 'Yu Gothic UI' });
  slide.addText(v.overallLabel || scoreBand(v.overallScore), { x: 0.3, y: BODY_TOP + 1.78, w: 3.1, h: 0.5, fontSize: 13, bold: true, color: scoreColor(v.overallScore), align: 'center', valign: 'middle', fontFace: 'Yu Gothic UI', wrap: true });

  // Executive summary text (right of score block)
  if (v.summary) {
    slide.addText([
      { text: 'Assessment.  ', options: { bold: true, color: t.titleText } },
      { text: truncate(v.summary, 620), options: { color: t.metaText } },
    ], { x: 3.7, y: BODY_TOP, w: W - 3.7 - 0.35, h: 2.35, fontSize: 12.5, fontFace: 'Yu Gothic UI', valign: 'top', wrap: true });
  }

  // Pillar maturity table (full width, below)
  const pillars = v.pillars.slice(0, 5);
  const pTop = BODY_TOP + 2.65;
  slide.addText('Pillar maturity', { x: 0.35, y: pTop, w: 6, h: 0.3, fontSize: 13, bold: true, color: t.titleText, fontFace: 'Yu Gothic UI' });
  const header = [
    { text: 'Pillar', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
    { text: 'Maturity', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
    { text: 'Score', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
  ];
  const rows = pillars.map((p) => [
    { text: p.pillar, options: { color: t.titleText } },
    { text: p.maturity || scoreBand(p.score), options: { color: t.metaText } },
    { text: `${Math.round(p.score)} / 100`, options: { color: scoreColor(p.score), bold: true, align: 'right' as const } },
  ]);
  slide.addTable([header, ...rows], {
    x: 0.35, y: pTop + 0.36, w: W - 0.7,
    colW: [4.2, 6.6, 1.83],
    fontSize: 12, fontFace: 'Yu Gothic UI',
    border: { type: 'solid', color: t.headerBg, pt: 1 }, valign: 'middle', rowH: 0.34,
  });
}

/** Slide 4b — WAF key findings & recommendations (only when findings exist). */
function addValidationFindingsSlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  const v = o.validation;
  if (!v || !v.findings.length) return;
  const slide = pptx.addSlide();
  addChrome(pptx, slide, t, 'Key findings & recommendations');

  const findings = v.findings.slice(0, 5);
  const rowH = (FOOTER_Y - BODY_TOP - 0.1) / findings.length;
  findings.forEach((f, i) => {
    const y = BODY_TOP + i * rowH;
    // Severity chip
    slide.addText(f.severity.toUpperCase(), { x: 0.35, y: y + 0.05, w: 1.05, h: 0.34, fontSize: 9, bold: true, color: 'ffffff', fill: { color: severityColor(f.severity) }, align: 'center', valign: 'middle', fontFace: 'Yu Gothic UI' });
    // Issue + recommendation
    slide.addText([
      { text: `${f.category}. `, options: { bold: true, color: t.titleText } },
      { text: truncate(f.issue, 170), options: { color: t.metaText } },
    ], { x: 1.55, y: y + 0.02, w: W - 1.95, h: rowH * 0.5, fontSize: 12, fontFace: 'Yu Gothic UI', valign: 'top', wrap: true });
    if (f.recommendation) {
      slide.addText([
        { text: '→ Fix:  ', options: { bold: true, color: t.accent } },
        { text: truncate(f.recommendation, 220), options: { color: t.metaText, italic: true } },
      ], { x: 1.55, y: y + rowH * 0.5, w: W - 1.95, h: rowH * 0.46, fontSize: 11, fontFace: 'Yu Gothic UI', valign: 'top', wrap: true });
    }
  });
}

/** Slide 5a — cost overview (only when cost provided). */
function addCostOverviewSlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  const c = o.cost;
  if (!c) return;
  const slide = pptx.addSlide();
  const meta = [c.term, c.region, c.pricesAsOf ? `prices as of ${c.pricesAsOf}` : undefined].filter(Boolean).join('  ·  ');
  addChrome(pptx, slide, t, 'Estimated cost', meta || undefined);

  // Headline monthly + annual
  slide.addText(money(c.totalMonthly, c.currency), { x: 0.35, y: BODY_TOP, w: 5.2, h: 0.95, fontSize: 46, bold: true, color: t.accent, fontFace: 'Yu Gothic UI' });
  slide.addText('per month (estimate)', { x: 0.37, y: BODY_TOP + 0.95, w: 5.2, h: 0.32, fontSize: 12, color: t.metaText, fontFace: 'Yu Gothic UI' });
  if (c.annual) {
    slide.addText(`≈ ${money(c.annual, c.currency)} / year`, { x: 0.37, y: BODY_TOP + 1.3, w: 5.2, h: 0.35, fontSize: 15, bold: true, color: t.titleText, fontFace: 'Yu Gothic UI' });
  }

  // Fixed vs usage-based split
  if (c.fixedCost != null && c.usageCost != null && c.totalMonthly > 0) {
    const fixedPct = Math.round((c.fixedCost / c.totalMonthly) * 100);
    const usagePct = 100 - fixedPct;
    const barY = BODY_TOP + 1.95;
    const barW = 5.0;
    slide.addText('Cost predictability', { x: 0.37, y: barY, w: 5.2, h: 0.3, fontSize: 12, bold: true, color: t.titleText, fontFace: 'Yu Gothic UI' });
    // stacked bar
    slide.addShape(pptx.ShapeType.rect, { x: 0.37, y: barY + 0.35, w: barW, h: 0.28, fill: { color: t.headerBg }, line: { width: 0 } });
    slide.addShape(pptx.ShapeType.rect, { x: 0.37, y: barY + 0.35, w: Math.max(0.02, barW * fixedPct / 100), h: 0.28, fill: { color: t.accent }, line: { width: 0 } });
    slide.addText([
      { text: `Fixed ${money(c.fixedCost, c.currency)} (${fixedPct}%)`, options: { color: t.accent, bold: true } },
      { text: `    ·    Usage-based ${money(c.usageCost, c.currency)} (${usagePct}%) — varies`, options: { color: t.metaText } },
    ], { x: 0.37, y: barY + 0.68, w: 5.2, h: 0.35, fontSize: 10, fontFace: 'Yu Gothic UI' });
  }

  slide.addText('Estimate only — not a quote. Excludes taxes, egress, support plans and reservations unless modeled.', { x: 0.37, y: FOOTER_Y - 0.5, w: 5.2, h: 0.45, fontSize: 9, italic: true, color: t.footerText, fontFace: 'Yu Gothic UI', wrap: true });

  // Top cost drivers table (right)
  const svcs = c.topServices.slice(0, 10);
  if (svcs.length) {
    const header = [
      { text: 'Top cost drivers', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
      { text: 'Tier', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
      { text: 'Monthly', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
      { text: 'Share', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
    ];
    const rows = svcs.map((s) => [
      { text: s.serviceName, options: { color: t.titleText } },
      { text: s.tier || '—', options: { color: t.metaText } },
      { text: money(s.cost, c.currency), options: { color: t.metaText, align: 'right' as const } },
      { text: s.percentage != null ? `${Math.round(s.percentage)}%` : '—', options: { color: t.metaText, align: 'right' as const } },
    ]);
    slide.addTable([header, ...rows], {
      x: 5.9, y: BODY_TOP, w: W - 5.9 - 0.35,
      colW: [3.3, 1.85, 1.15, 0.78],
      fontSize: 12, fontFace: 'Yu Gothic UI',
      border: { type: 'solid', color: t.headerBg, pt: 1 }, valign: 'middle', rowH: 0.32,
    });
  }
}

/** Slide 5b — multi-region cost comparison (only when >1 region computed). */
function addCostRegionsSlide(pptx: PptxGenJS, t: SlideTheme, o: ArchitectureDeckOptions): void {
  const c = o.cost;
  if (!c || !c.regions || c.regions.length < 2) return;
  const slide = pptx.addSlide();
  addChrome(pptx, slide, t, 'Regional cost comparison', c.term || undefined);

  const cheapest = c.regions.find(r => r.isCheapest) || c.regions[0];
  const current = c.regions.find(r => r.isCurrent);
  if (cheapest) {
    const onCheapest = current && current.name === cheapest.name;
    const msg = onCheapest
      ? `Already on the cheapest region — ${cheapest.flag || ''} ${cheapest.name} at ${money(cheapest.monthly, c.currency)}/mo.`
      : `Cheapest region: ${cheapest.flag || ''} ${cheapest.name} at ${money(cheapest.monthly, c.currency)}/mo` +
        (current ? `  ·  potential saving ${money(current.monthly - cheapest.monthly, c.currency)}/mo` : '');
    slide.addText(msg, { x: 0.35, y: BODY_TOP, w: W - 0.7, h: 0.45, fontSize: 13, bold: true, color: t.accent, fontFace: 'Yu Gothic UI', valign: 'middle' });
  }

  const rows = c.regions.slice(0, 8).map((r) => {
    const tag = r.isCheapest ? '  ★' : r.isCurrent ? '  (current)' : '';
    const vsCheapest = cheapest && cheapest.monthly > 0
      ? (r.monthly === cheapest.monthly ? 'baseline' : `+${(((r.monthly - cheapest.monthly) / cheapest.monthly) * 100).toFixed(1)}%`)
      : '—';
    return [
      { text: `${r.flag || ''} ${r.name}${tag}`, options: { color: t.titleText, bold: !!r.isCheapest } },
      { text: money(r.monthly, c.currency), options: { color: t.metaText, align: 'right' as const } },
      { text: money(r.annual, c.currency), options: { color: t.metaText, align: 'right' as const } },
      { text: vsCheapest, options: { color: t.metaText, align: 'right' as const } },
    ];
  });
  const header = [
    { text: 'Region', options: { bold: true, color: 'ffffff', fill: { color: t.accent } } },
    { text: 'Monthly', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
    { text: 'Annual', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
    { text: 'vs cheapest', options: { bold: true, color: 'ffffff', fill: { color: t.accent }, align: 'right' as const } },
  ];
  slide.addTable([header, ...rows], {
    x: 0.35, y: BODY_TOP + 0.6, w: W - 0.7,
    colW: [6.13, 2.0, 2.0, 1.5],
    fontSize: 12, fontFace: 'Yu Gothic UI',
    border: { type: 'solid', color: t.headerBg, pt: 1 }, valign: 'middle', rowH: 0.36,
  });
}

/**
 * Build and download a multi-slide, customer-ready PPTX deck for the current
 * architecture: title, diagram, services, and (when available) a Well-Architected
 * review (summary + findings) and a cost estimate (overview + regional
 * comparison). Returns the generated filename.
 */
export async function exportArchitectureDeck(
  imageDataUrl: string,
  options: ArchitectureDeckOptions,
): Promise<string> {
  const t = options.isDarkMode ? DARK_THEME : LIGHT_THEME;

  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = options.author;
  pptx.title = options.diagramName;
  pptx.subject = 'Azure Architecture Review';
  pptx.company = 'Microsoft Azure';

  addTitleSlide(pptx, t, options);
  addDiagramSlide(pptx, t, imageDataUrl, options);
  addServicesSlide(pptx, t, options);
  addValidationSummarySlide(pptx, t, options);
  addValidationFindingsSlide(pptx, t, options);
  addCostOverviewSlide(pptx, t, options);
  addCostRegionsSlide(pptx, t, options);

  const fileName = generateModelFilename('azure-architecture-deck', 'pptx');
  await pptx.writeFile({ fileName });
  return fileName;
}
