// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Workflow Narrative Exporter
 * ---------------------------
 * Builds a Markdown document describing the current architecture and its
 * workflow narrative (the step-by-step data/process flow shown in the Workflow
 * panel), so users can save/share the design as prose alongside the diagram.
 *
 * Pure and additive: takes a snapshot of the diagram state and returns a
 * Markdown string. The caller triggers the download (mirrors exportAsSvg).
 */

import type { Node, Edge } from 'reactflow';

export interface WorkflowNarrativeInput {
  title: {
    architectureName: string;
    author: string;
    version: string;
    date: string;
  };
  prompt?: string;
  model?: { name: string; timeMs?: number } | null;
  nodes: Node[];
  edges: Edge[];
  workflow: Array<{ step: number; description: string; services: string[] }>;
  /** Optional WAF score (0-100) if the diagram has been validated. */
  validationScore?: number | null;
  /** Optional total monthly cost estimate. */
  totalMonthlyCost?: number;
  pricingMode?: string;
  region?: string;
}

/**
 * Escape user text so Markdown renders it as the characters the user typed.
 *
 * Service names and descriptions routinely contain the characters Markdown
 * treats as syntax. `<...>` is swallowed as unknown HTML, so "Function App
 * <v2>" simply loses the version. A backtick opens a code span that runs to the
 * next one, which silently swallows everything between two services. `*` and
 * `_` around a word turn it italic and disappear, `[a](b)` becomes a link, and
 * `&copy;` becomes a ©.
 *
 * Only the characters that mean something *mid-line* are escaped. Every value
 * here is interpolated after a heading marker, a list bullet or a table pipe,
 * never at the start of a line, so `#`, `-`, `+` and `.` cannot start a block
 * and are left alone — escaping them would litter ordinary product names with
 * backslashes for no gain.
 */
function mdText(value: string): string {
  return (value || '').replace(/([\\`*_[\]<>|~&])/g, '\\$1');
}

/** Escape a value for safe use inside a Markdown table cell. */
function cell(value: string): string {
  return mdText(value).replace(/\s*[\r\n]+\s*/g, ' ').trim();
}

/**
 * Build a Markdown narrative for the given architecture snapshot.
 */
export function buildWorkflowMarkdown(input: WorkflowNarrativeInput): string {
  const {
    title,
    prompt,
    model,
    nodes,
    edges,
    workflow,
    validationScore,
    totalMonthlyCost,
    pricingMode,
    region,
  } = input;

  const serviceNodes = nodes.filter((n) => n.type === 'azureNode');
  const groupNodes = nodes.filter((n) => n.type === 'groupNode');

  // id -> display label (service type) for resolving workflow/connection refs.
  const labelById = new Map<string, string>();
  for (const n of nodes) {
    const label = (n.data as any)?.label;
    if (label) labelById.set(n.id, String(label));
  }

  // Resolve a workflow service ref (node id OR label) to a readable name.
  const resolveRef = (ref: string): string => labelById.get(ref) ?? ref;

  const lines: string[] = [];

  // ── Header ────────────────────────────────────────────────────────────
  lines.push(`# ${cell(title.architectureName || '') || 'Untitled Architecture'}`);
  lines.push('');
  const meta = [`**Author:** ${cell(title.author || '') || 'Azure Architect'}`, `**Version:** ${cell(title.version || '') || '1.0'}`, `**Date:** ${cell(title.date || '') || new Date().toLocaleDateString()}`];
  if (model?.name) {
    meta.push(`**Model:** ${cell(model.name)}${model.timeMs ? ` (${(model.timeMs / 1000).toFixed(1)}s)` : ''}`);
  }
  lines.push(meta.join(' · '));
  lines.push('');
  lines.push('> Generated by the Microsoft Product Architecture Diagram Builder.');
  lines.push('');

  // ── Overview / prompt ───────────────────────────────────────────────────
  if (prompt && prompt.trim()) {
    lines.push('## Overview');
    lines.push('');
    // A prompt is prose the user typed; keep its line breaks but do not let a
    // stray angle bracket or backtick eat the rest of the paragraph.
    lines.push(mdText(prompt.trim()));
    lines.push('');
  }

  // ── Services (grouped when the diagram uses groups) ──────────────────────
  lines.push(`## Services (${serviceNodes.length})`);
  lines.push('');
  if (serviceNodes.length === 0) {
    lines.push('_No services on the canvas yet._');
    lines.push('');
  } else if (groupNodes.length > 0) {
    for (const group of groupNodes) {
      const groupLabel = (group.data as any)?.label || 'Group';
      const members = serviceNodes.filter((n) => n.parentNode === group.id);
      if (members.length === 0) continue;
      lines.push(`### ${cell(String(groupLabel))}`);
      lines.push('');
      for (const n of members) {
        const desc = (n.data as any)?.description;
        lines.push(`- **${cell(String((n.data as any)?.label ?? 'Service'))}**${desc ? ` — ${cell(String(desc))}` : ''}`);
      }
      lines.push('');
    }
    const ungrouped = serviceNodes.filter((n) => !n.parentNode || !groupNodes.some((g) => g.id === n.parentNode));
    if (ungrouped.length > 0) {
      lines.push('### Ungrouped');
      lines.push('');
      for (const n of ungrouped) {
        const desc = (n.data as any)?.description;
        lines.push(`- **${cell(String((n.data as any)?.label ?? 'Service'))}**${desc ? ` — ${cell(String(desc))}` : ''}`);
      }
      lines.push('');
    }
  } else {
    for (const n of serviceNodes) {
      const desc = (n.data as any)?.description;
      lines.push(`- **${cell(String((n.data as any)?.label ?? 'Service'))}**${desc ? ` — ${cell(String(desc))}` : ''}`);
    }
    lines.push('');
  }

  // ── Workflow narrative ───────────────────────────────────────────────────
  lines.push('## Workflow');
  lines.push('');
  if (!workflow || workflow.length === 0) {
    lines.push('_No workflow steps defined for this diagram._');
    lines.push('');
  } else {
    const ordered = [...workflow].sort((a, b) => (a.step ?? 0) - (b.step ?? 0));
    for (const s of ordered) {
      lines.push(`${s.step}. ${cell(String(s.description ?? ''))}`);
      if (Array.isArray(s.services) && s.services.length > 0) {
        const names = s.services.map(resolveRef);
        lines.push(`   - _Services:_ ${names.map((name) => cell(String(name))).join(' → ')}`);
      }
    }
    lines.push('');
  }

  // ── Connections ──────────────────────────────────────────────────────────
  if (edges.length > 0) {
    lines.push(`## Connections (${edges.length})`);
    lines.push('');
    lines.push('| From | To | Label |');
    lines.push('| --- | --- | --- |');
    for (const e of edges) {
      const from = labelById.get(e.source) ?? e.source;
      const to = labelById.get(e.target) ?? e.target;
      const label = typeof e.label === 'string' ? e.label : '';
      lines.push(`| ${cell(from)} | ${cell(to)} | ${cell(label)} |`);
    }
    lines.push('');
  }

  // ── Optional: validation + cost summary ──────────────────────────────────
  if (typeof validationScore === 'number') {
    lines.push('## Well-Architected Validation');
    lines.push('');
    lines.push(`**Score:** ${validationScore}/100`);
    lines.push('');
  }
  if (
    typeof totalMonthlyCost === 'number'
    && totalMonthlyCost >= 0
    && serviceNodes.some(node => Boolean(node.data?.pricing))
  ) {
    lines.push('## Estimated Monthly Cost');
    lines.push('');
    const term = pricingMode === 'reserved1yr' ? '1-year savings plan' : 'pay-as-you-go';
    const where = region ? `, ${region}` : '';
    lines.push(`Approximately **$${totalMonthlyCost.toLocaleString(undefined, { maximumFractionDigits: 0 })}/mo** (${term}${where}).`);
    lines.push('');
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push(`_Exported ${new Date().toISOString()}._`);
  lines.push('');

  return lines.join('\n');
}
