
#!/usr/bin/env bash
export AZURE_RESOURCE_GROUP="azure-diagrams-rg"
export AZURE_LOCATION="eastus2"
export CONTAINER_APP_ENVIRONMENT="aca-env-azure-diagrams-vnet"
export AZURE_CONTAINER_REGISTRY="acrazurediagrams1767583743"
export ANALYTICS_LOG_ANALYTICS_WORKSPACE="workspace-azurediagramsrgbuvF"
export SOURCE_LOG_ANALYTICS_WORKSPACE_RESOURCE_GROUP="DefaultResourceGroup-EUS2"
export SOURCE_LOG_ANALYTICS_WORKSPACE="DefaultWorkspace-<subscription-id>-EUS2"
export ANALYTICS_APP_NAME="aadb-usage-analytics"
export ANALYTICS_IDENTITY_NAME="id-aadb-usage-analytics"
export ANALYTICS_ENTRA_APP_NAME="AADB Product Analytics"
export AZURE_COSMOS_ENDPOINT=""
export AZURE_COSMOS_ACCOUNT_NAME=""
export COSMOS_DATABASE_ID="diagrams-db"
export AZURE_OPENAI_ENDPOINT=""
export AZURE_OPENAI_DEPLOYMENT=""
export AZURE_OPENAI_RESOURCE_GROUP=""
export AZURE_OPENAI_RESOURCE_NAME=""